services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: weather_bot
    env_file: .env
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: weather_bot_db
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
